Lecture 1
newDmoon/phoneshop-servlet-api pull request #1
Opened 2022-01-25 16:13 UTC by newDmoon

Made complete task 1.5, 1.6

2022-01-26 12:28 UTC, devjohnsmith1 requested changes

2022-01-26 12:28 UTC, devjohnsmith1 commented on src/main/java/com/es/phoneshop/model/product/ArrayListProductDao.java
> +                return null;
проставь скобки

2022-01-26 12:28 UTC, devjohnsmith1 commented on src/main/java/com/es/phoneshop/model/product/ArrayListProductDao.java
> +                return null;
+ почему возвращаем null? Optional? Exception?

2022-01-26 12:28 UTC, devjohnsmith1 commented on src/main/java/com/es/phoneshop/model/product/ArrayListProductDao.java
> +                    .filter(product -> id.equals(product.getId()))
что если id пустой?

2022-01-26 12:28 UTC, devjohnsmith1 commented on src/main/java/com/es/phoneshop/model/product/ArrayListProductDao.java
> +    private long maxId;
поле нигде не инициализируется?

2022-01-26 12:28 UTC, devjohnsmith1 commented on src/main/java/com/es/phoneshop/model/product/ArrayListProductDao.java
> +                }
перепиши на стримы

2022-01-26 12:28 UTC, devjohnsmith1 commented on src/main/java/com/es/phoneshop/model/product/ArrayListProductDao.java
> +                    product.setId(maxId++);
нельзя ли вынести генерацию id в отдельный метод для наглядности?

2022-01-26 12:28 UTC, devjohnsmith1 commented on src/main/java/com/es/phoneshop/model/product/ArrayListProductDao.java
> +            if (id != null) {
а если нет такого продукта?

2022-01-26 12:28 UTC, devjohnsmith1 commented on src/main/java/com/es/phoneshop/model/product/Product.java
> +    }
слишком много полей в конструкторе

2022-01-26 12:28 UTC, devjohnsmith1 commented on src/main/java/com/es/phoneshop/web/ProductListPageServlet.java
> +        request.getRequestDispatcher("/WEB-INF/pages/productList.jsp").forward(request, response);
выноси hardcode в константы

2022-01-26 12:28 UTC, devjohnsmith1 commented on src/test/java/com/es/phoneshop/model/product/ArrayListProductDaoTest.java
>      private ProductDao productDao;
обязательно ли использовать реальный productDao?

2022-01-26 12:28 UTC, devjohnsmith1 commented on src/test/java/com/es/phoneshop/model/product/ArrayListProductDaoTest.java
> +        assertEquals("test-product", result.getCode());
константы + названия тестовых методов

2022-01-26 12:28 UTC, devjohnsmith1 commented on src/test/java/com/es/phoneshop/web/ProductListPageServletTest.java
> +import static org.mockito.ArgumentMatchers.*;
лишние импорты

2022-01-26 12:28 UTC, devjohnsmith1 commented on src/test/java/com/es/phoneshop/web/ProductListPageServletTest.java
> +        verify(request).setAttribute(eq("products"), any());
константы

2022-01-28 21:44 UTC, devjohnsmith1 requested changes

2022-01-28 21:44 UTC, devjohnsmith1 commented on tatus
> +[33mcommit becfdc9f73dc701877b354826476578d6b929e82[m[33m ([m[1;36mHEAD -> [m[1;32mlecture-1[m[33m, [m[1;31morigin/lecture-1[m[33m)[m
Разреши конфликты и проверяй файлы перед коммитом

2022-01-28 21:44 UTC, devjohnsmith1 commented on src/main/java/com/es/phoneshop/model/product/ArrayListProductDao.java
> +            }
не путай эксепшны - NoSuchElementException используется, если нет такого элемента. Подумай, валидный ли id = null + что делать, когда продукта с таким id нет? Optional? Exception?

2022-01-28 21:44 UTC, devjohnsmith1 commented on src/main/java/com/es/phoneshop/model/product/ArrayListProductDao.java
> +    public void save(Product product) throws NoSuchElementException {
Почему save кидает эксепшн, что такого элемента нет?

2022-01-28 21:44 UTC, devjohnsmith1 commented on src/main/java/com/es/phoneshop/model/product/ArrayListProductDao.java
> +                                .filter(product1 -> product.getId().equals(product1.getId()))
Переименуй product1 - для чего переменная?

2022-01-28 21:44 UTC, devjohnsmith1 commented on src/main/java/com/es/phoneshop/model/product/ArrayListProductDao.java
>                      }
плохая практика (когда мы должны использовать эксепшны и для чего?)

2022-01-28 21:44 UTC, devjohnsmith1 commented on src/main/java/com/es/phoneshop/model/product/ArrayListProductDao.java
> +                        products.set(products.indexOf(products.stream()
зачем нам set?

2022-01-28 21:44 UTC, devjohnsmith1 commented on src/main/java/com/es/phoneshop/model/product/ArrayListProductDao.java
> +                throw new NoSuchElementException();
delete кидает NoSuchElementException?

2022-01-28 21:44 UTC, devjohnsmith1 commented on src/test/java/com/es/phoneshop/model/product/ArrayListProductDaoTest.java
> +    public void SaveProduct_IfExistsWithIdMoreThanZero_AssertCompile() {
ничего не понятно. Названия перепиши на java - style (camel case) + используй структуру, что я давал

2022-01-28 21:44 UTC, devjohnsmith1 commented on src/test/java/com/es/phoneshop/model/product/ArrayListProductDaoTest.java
> +        Product product = new Product("test-product", "Samsung Galaxy S", new BigDecimal(100), USD, 100, "https://raw.githubusercontent.com/andrewosipenko/phoneshop-ext-images/master/manufacturer/Sam
вынеси в константы

2022-01-28 21:44 UTC, devjohnsmith1 commented on src/test/java/com/es/phoneshop/model/product/ArrayListProductDaoTest.java
> +    public void DeleteProduct_IfExists_ThrowsException() {
название

2022-01-28 21:44 UTC, devjohnsmith1 commented on src/test/java/com/es/phoneshop/model/product/ArrayListProductDaoTest.java
> +        Product product = new Product("test-product", "Samsung Galaxy S", new BigDecimal(100), USD, 100, "https://raw.githubusercontent.com/andrewosipenko/phoneshop-ext-images/master/manufacturer/Sam
constants

2022-01-28 21:44 UTC, devjohnsmith1 commented on src/test/java/com/es/phoneshop/model/product/ArrayListProductDaoTest.java
>          assertEquals("test-product", result.getCode());
константы

2022-01-28 21:44 UTC, devjohnsmith1 commented on src/test/java/com/es/phoneshop/model/product/ArrayListProductDaoTest.java
>  public class ArrayListProductDaoTest {
используй junit + mockito

2022-01-30 15:16 UTC, newDmoon commented on src/main/java/com/es/phoneshop/model/product/ArrayListProductDao.java
> +                        products.set(products.indexOf(products.stream()
если продукт с таким айди уже был в листе, то должна произойти замена продукта из списка на передадваемый

2022-01-31 11:32 UTC, newDmoon commented on src/main/java/com/es/phoneshop/model/product/ArrayListProductDao.java
>                      }
в данном случае, если мы не замещаем 1 продукт другим, значит мы просто его добавляем в наш список

2022-01-31 13:04 UTC, devjohnsmith1 approved these changes

2022-01-31 13:25 UTC, merged