Task 4
newDmoon/phoneshop-servlet-api pull request #4
Opened 2022-02-16 14:47 UTC by newDmoon

2022-02-17 12:42 UTC, devjohnsmith1 requested changes

2022-02-17 12:42 UTC, devjohnsmith1 commented on src/main/java/com/es/phoneshop/service/cart/impl/CartSessionServiceImpl.java
> +//                .map());
посмотри такой метод стримов как Stream.reduce()

2022-02-17 12:42 UTC, devjohnsmith1 commented on src/main/java/com/es/phoneshop/web/CartPageServlet.java
> +        if (e.getClass().equals(NumberFormatException.class)) {
используй instanceof в обоих случаях

2022-02-17 12:42 UTC, devjohnsmith1 commented on src/main/java/com/es/phoneshop/web/CartPageServlet.java
> +                errors.put(productId, "Out of stock, max available " + ((OutOfStockException) e).getStockRequested());
локализация

2022-02-17 12:42 UTC, devjohnsmith1 commented on src/main/java/com/es/phoneshop/web/CartPageServlet.java
> +            if (((OutOfStockException) e).getStockRequested() <= 0) {
лучше не хранить параметр в эксепшне. Максимум сообщение

2022-02-17 12:42 UTC, devjohnsmith1 commented on src/main/java/com/es/phoneshop/web/DeleteCartItemServlet.java
> +public class DeleteCartItemServlet extends HttpServlet {
из названия нужно понимать, на какой это странице

2022-02-17 12:42 UTC, devjohnsmith1 commented on src/main/java/com/es/phoneshop/web/DeleteCartItemServlet.java
> +    private final String MESSAGE_PARAMETER_SUCCESS_PRODUCT_ADD_TO_CART = "/cart?message=Cart item removed successfully";
не передавай сообщение параметром запроса

2022-02-17 12:42 UTC, devjohnsmith1 commented on src/main/java/com/es/phoneshop/web/MiniCartServlet.java
> +public class MiniCartServlet extends HttpServlet {
Page

2022-02-17 12:42 UTC, devjohnsmith1 commented on src/main/java/com/es/phoneshop/web/ProductListPageServlet.java
> +        String productInfo = request.getPathInfo().substring(START_INDEX_WITHOUT_SLASH);
тогда уже что-то вроде productIdString

2022-02-17 12:42 UTC, devjohnsmith1 commented on src/main/java/com/es/phoneshop/web/ProductListPageServlet.java
> +        return quantity;
разделяй код визуально для читаемости

2022-02-17 12:42 UTC, devjohnsmith1 commented on src/main/java/com/es/phoneshop/web/ProductListPageServlet.java
> +        return quantity;
+ валидацию quantity лучше вынести отдельно

2022-02-17 12:42 UTC, devjohnsmith1 commented on src/main/webapp/WEB-INF/pages/cart.jsp
> +                <td></td>
почитай про colspan

2022-02-17 12:44 UTC, devjohnsmith1 commented
+ тесты, локализация, константы

2022-02-17 12:56 UTC, newDmoon commented on src/main/java/com/es/phoneshop/web/MiniCartServlet.java
> +public class MiniCartServlet extends HttpServlet {
это же не страница

2022-02-22 10:28 UTC, devjohnsmith1 approved these changes

2022-02-22 10:28 UTC, merged